version: '3.4'

services:
  db:
    image: apirest-aspnet5-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: apirest_aspnet5
    ports:
      - 3308:3306
    networks:
      - vo-network

  apirest-aspnet5:
    image: apirest-aspnet5
    build:
      context: .
      dockerfile: VODocker/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80
    depends_on:
      - db
    networks:
      - vo-network

networks:
  vo-network:
    driver: bridge